- name: Player’s Handbook
  source: PHB
- name: Sword Coast Adveturer’s Guide
  source: SCAG
- name: Elemental Evil Player’s Companion
  source: EE
- name: Xanathar’s Guide to Everything
  source: XGE
- name: Tasha’s Cauldron of Everything
  source: TCE
- name: Fizban’s Treasury of Dragons
  source: FTD
- name: "Strixhaven: A Curriculum of Chaos"
  source: SCC
- name: "Explorer’s Guide to Wildemount"
  source: EGW
- name: "Acquisitions Incorporated"
  source: AI
- name: "Astral Adventurer’s Guide"
  source: AAG
- name: "Guildmasters’ Guide to Ravnica"
  source: GGR
- name: "Icewind Dale: Rime of the Frostmaiden"
  source: IDRF
- name: "Adventures in the Forgotten Realms: A Verdant Tomb"
  source: AVT
- name: "Adventures in the Forgotten Realms: From Cyan Depths"
  source: FCD
- name: "Lost Laboratory of Kwalish"
  source: LLK
